//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tess.Common {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Traduzioni {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Traduzioni() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tess.Common.Traduzioni", typeof(Traduzioni).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tess v1.0.
        /// </summary>
        internal static string About_heading {
            get {
                return ResourceManager.GetString("About_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tess, made by Carlo Camagni. 
        ///Tess is developed in C# and Xamarin, for source code visit https://github.com/camo81/Tess.
        ///You are free to download, modify, destroy or improve it.
        ///Thanks to Material Design Icons (https://materialdesignicons.com/) for in app icons, Pixabay (https://pixabay.com/it/) for menu background, Smashicons on Flaticon (https://www.flaticon.com/authors/smashicons) for the app icon.
        ///And to my daughter Teresa, this app is for you &lt;3..
        /// </summary>
        internal static string About_text {
            get {
                return ResourceManager.GetString("About_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Worked hours in week.
        /// </summary>
        internal static string Detail_l1 {
            get {
                return ResourceManager.GetString("Detail_l1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Day/hours in week.
        /// </summary>
        internal static string Detail_l2 {
            get {
                return ResourceManager.GetString("Detail_l2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reqested week hours.
        /// </summary>
        internal static string Detail_l3 {
            get {
                return ResourceManager.GetString("Detail_l3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Working days in week.
        /// </summary>
        internal static string Detail_l4 {
            get {
                return ResourceManager.GetString("Detail_l4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remaining hours.
        /// </summary>
        internal static string Detail_l5 {
            get {
                return ResourceManager.GetString("Detail_l5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You shall not pass.
        /// </summary>
        internal static string Entry_gandalf {
            get {
                return ResourceManager.GetString("Entry_gandalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://github.com/camo81/Tess.
        /// </summary>
        internal static string General_GitUri {
            get {
                return ResourceManager.GetString("General_GitUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Choose language.
        /// </summary>
        internal static string Language_pickerTitle {
            get {
                return ResourceManager.GetString("Language_pickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Making some stuff... | Round one, fight! |Tthese aren&apos;t the droids you&apos;re looking for | That is why you fail.|Adventure. Excitement. A Jedi craves not these things|Wars not make one great. | Do. Or do not. There is no try.| Always two there are, no more, no less. A master and an apprentice.|You fail because you don’t believe..
        /// </summary>
        internal static string Loading_message {
            get {
                return ResourceManager.GetString("Loading_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a First close the opened Check-in.
        /// </summary>
        internal static string Main_1opened {
            get {
                return ResourceManager.GetString("Main_1opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error casting to int.
        /// </summary>
        internal static string Main_castError {
            get {
                return ResourceManager.GetString("Main_castError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Done.
        /// </summary>
        internal static string Main_Closed {
            get {
                return ResourceManager.GetString("Main_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ahr ahr ahr, I&apos;m Pirate Roberts!.
        /// </summary>
        internal static string Main_confirm_no {
            get {
                return ResourceManager.GetString("Main_confirm_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Go to settings page.
        /// </summary>
        internal static string Main_confirm_yes {
            get {
                return ResourceManager.GetString("Main_confirm_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a To proced you must set the required values.
        /// </summary>
        internal static string Main_confirmMessage {
            get {
                return ResourceManager.GetString("Main_confirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a openedHours is null or &gt;2.
        /// </summary>
        internal static string Main_countError {
            get {
                return ResourceManager.GetString("Main_countError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Done.
        /// </summary>
        internal static string Main_insert {
            get {
                return ResourceManager.GetString("Main_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error on insert checkout.
        /// </summary>
        internal static string Main_insertError {
            get {
                return ResourceManager.GetString("Main_insertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error on insert checkin.
        /// </summary>
        internal static string Main_insertError2 {
            get {
                return ResourceManager.GetString("Main_insertError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error: More than 1 check-in active.
        /// </summary>
        internal static string Main_moreThan1 {
            get {
                return ResourceManager.GetString("Main_moreThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Max Check-in / day is 2.
        /// </summary>
        internal static string Main_moreThan2 {
            get {
                return ResourceManager.GetString("Main_moreThan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nothing to close..
        /// </summary>
        internal static string Main_noToClose {
            get {
                return ResourceManager.GetString("Main_noToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Language.
        /// </summary>
        internal static string Menu_language {
            get {
                return ResourceManager.GetString("Menu_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Main.
        /// </summary>
        internal static string Menu_main {
            get {
                return ResourceManager.GetString("Menu_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settings.
        /// </summary>
        internal static string Menu_settings {
            get {
                return ResourceManager.GetString("Menu_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No.
        /// </summary>
        internal static string Setting_confirm_no {
            get {
                return ResourceManager.GetString("Setting_confirm_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Yes.
        /// </summary>
        internal static string Setting_confirm_yes {
            get {
                return ResourceManager.GetString("Setting_confirm_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure to proceed?.
        /// </summary>
        internal static string Setting_confirmMessage {
            get {
                return ResourceManager.GetString("Setting_confirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You can&apos;t work more than 15 hours per day.
        /// </summary>
        internal static string Settings_LavoriTroppo {
            get {
                return ResourceManager.GetString("Settings_LavoriTroppo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nothing to do..
        /// </summary>
        internal static string Settings_Nothing {
            get {
                return ResourceManager.GetString("Settings_Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Working days in week *.
        /// </summary>
        internal static string Settings_picker1 {
            get {
                return ResourceManager.GetString("Settings_picker1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Working hours in week *.
        /// </summary>
        internal static string Settings_picker2 {
            get {
                return ResourceManager.GetString("Settings_picker2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hour.
        /// </summary>
        internal static string Settings_picker3 {
            get {
                return ResourceManager.GetString("Settings_picker3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Minute.
        /// </summary>
        internal static string Settings_picker4 {
            get {
                return ResourceManager.GetString("Settings_picker4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a If required, the minimun lenght of the break.
        /// </summary>
        internal static string Settings_pickerDesc {
            get {
                return ResourceManager.GetString("Settings_pickerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Working days in week and Working hours in week required!.
        /// </summary>
        internal static string Settings_SaveSetKo {
            get {
                return ResourceManager.GetString("Settings_SaveSetKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Done.
        /// </summary>
        internal static string Settings_SaveSetOk {
            get {
                return ResourceManager.GetString("Settings_SaveSetOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Play sounds.
        /// </summary>
        internal static string Settings_sound {
            get {
                return ResourceManager.GetString("Settings_sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
    }
}
